#name: Deploy Lambda Function
#on: [push]
  ##push:
    ##paths:
     ## - userguide.md

#jobs:

  #lint:
    #runs-on: ubuntu-latest
    #steps: 
      #- name: Check out code
        #uses: actions/checkout@v2
      #- name: Set up Python
        #uses: actions/setup-python@v2
        #with:
          #python-version: 3.8
      #- name: Install libraries
        #run: pip install flake8
      #- name: Lint with flake8
        #run: |
            #cd function
            #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  #build:
    #runs-on: ubuntu-latest
    #needs: lint
    #steps:
      #- name: Check out code
        #uses: actions/checkout@v2
      #- name: Set up Python
        #uses: actions/setup-python@v2
        #with:
          #python-version: 3.8
      #- name: Install libraries
        #run: |
            #cd function
            #python -m pip install --upgrade pip
            #if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi 
      #- name: Zip bundle
        #run: |
            #cd function
            #zip -r ../${{ github.sha }}.zip .
      #- name: Archive artifact
        #uses: actions/upload-artifact@v2
        #with:
          #name: zipped-bundle
          #path: ${{ github.sha }}.zip

          
  #documentation:
    #runs-on: ubuntu-latest
    #needs: lint
    #steps:
      #- name: Checkout code
        #uses: actions/checkout@v2
      #- name: Create docs folder
        #run: mkdir docs
      #- name: Convert md to html
        #uses: docker://pandoc/core:2.9
        #with:
          #args: userguide.md -t html -o docs/index.html
      #- name: Deploy Pages site
        #uses: JamesIves/github-pages-deploy-action@4.1.4
        #with:
          #branch: gh-pages
          #folder: docs

  #convert_via_pandoc:
    #name: Convert via Pandoc
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- run: mkdir output
      #- run: echo "foo" > input.txt
      #- uses: maxheld83/pandoc@v2
        #with:
          #args: "--standalone --output=output/index.html input.txt"
      #- uses: actions/upload-artifact@master
        #with:
          #name: output
          #path: output        


name: test 
on:
  workflow_dispatch:
   inputs:
      username:
        description: 'Your GitHub username'
        required: true
      reason:
        description: 'Why are you running this workflow manually?'
        required: true
        default: 'I am running tests before implementing an automated workflow'
